<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>LÖVE: version 1.1 by mrfrench@frenchmoustache.com including Lua Syntax: version 0.8 by gavin@refinery.com</string>
	<key>fileTypes</key>
	<array>
		<string>lua</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\b(function|if|for)\b|{</string>
	<key>foldingStopMarker</key>
	<string>\bend\b|}</string>
	<key>name</key>
	<string>LÖVE</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.lua</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.scope.function.lua</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.lua</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.lua</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(function)\s+([a-zA-Z_.:]+[.:])?([a-zA-Z_]\w*)\s*\(([^)]*)\)</string>
			<key>name</key>
			<string>meta.function.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+(\.\d+)?([eE]-?\d+)?|\.\d+([eE]-?\d+)?</string>
			<key>name</key>
			<string>constant.numeric.lua</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.lua</string>
			<key>swallow</key>
			<string>\\.</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.lua</string>
			<key>swallow</key>
			<string>\\.</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!--)\[\[</string>
			<key>end</key>
			<string>\]\]</string>
			<key>name</key>
			<string>string.quoted.multiline.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nested-string-multiline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>--\[\[</string>
			<key>end</key>
			<string>\]\]</string>
			<key>name</key>
			<string>comment.block.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nested-comment-multiline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>--(?!\[\[).*</string>
			<key>name</key>
			<string>comment.line.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(break|do|else|for|if|elseif|return|then|repeat|while|until|end|function|local|in|arg)\b</string>
			<key>name</key>
			<string>keyword.control.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(false|nil|true|self|_G)\b</string>
			<key>name</key>
			<string>constant.language.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![.:])\b(assert|collectgarbage|dofile|error|getfenv|getmetatable|gcinfo|ipairs|loadfile|loadlib|loadstring|next|pairs|pcall|print|rawequal|rawget|rawset|requie|setfenv|setmetatable|tonumber|tostring|type|unpack|xpcall)\b(?=\()</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![.:])\b(coroutine\.(create|resume|status|wrap|yield)|string\.(byte|char|dump|find|len|lower|rep|sub|upper|format|gfind|gsub)|table\.(concat|foreachi?|[gs]etn|sort|insert|remove)|math\.(abs|acos|asin|atan2?|ceil|cos|deg|exp|floor|log|log10|max|min|mod|pow|rad|sin|sqrt|tan|frexp|ldexp|random|randomseed)|io\.(close|flush|input|lines|open|output|read|tmpfile|type|write)|os\.(clock|date|difftime|execute|exit|getenv|remove|rename|setlocale|time|tmpname)|debug\.(debug|[gs]ethook|getinfo|[gs]etlocal|[gs]etupvalue|traceback))\b(?=\()</string>
			<key>name</key>
			<string>support.function.library</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|or)\b</string>
			<key>name</key>
			<string>keyword.operator.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|\*|\/|\^|==?|~=|&lt;=?|&gt;=?</string>
			<key>name</key>
			<string>entity.other</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>nested-comment-multiline</key>
		<dict>
			<key>begin</key>
			<string>\[\[</string>
			<key>end</key>
			<string>\]\]</string>
			<key>name</key>
			<string>comment.block.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nested-comment-multiline</string>
				</dict>
			</array>
		</dict>
		<key>nested-string-multiline</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!--)\[\[</string>
			<key>end</key>
			<string>\]\]</string>
			<key>name</key>
			<string>string.quoted.multiline.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nested-string-multiline</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lua</string>
	<key>uuid</key>
	<string>93E017CC-6F27-11D9-90EB-000D93589AF7</string>
</dict>
</plist>
