d = 'display'
t = 'tool_tip'
i = 'insert'
@choices = [
        {d => 'love.'},
       {d => 'love.load', t => 'called when the game first loads. ... = command-line data', i => '(...)'},
       {d => 'love.run', t => 'contains the main loop by default', i => '()'},
       {d => 'love.update', t => 'called every frame.<br><strong>dt</strong>:number = time since last frame', i => '( dt )'},
       {d => 'love.draw', t => 'called every frame to draw objects', i => '()'},
       {d => 'love.keypressed', t => 'called when a key is pressed.<br><strong>key</strong>:KeyConstant = character of the key pressed<br><strong>unicode</strong>:number = the unicode of the key pressed.', i => '( key, unicode )'},
       {d => 'love.keyreleased', t => 'called when a key is released.<br><strong>key</strong>:KeyConstant = character of the key pressed<br><strong>unicode</strong>:number = the unicode of the key pressed.', i => '( key, unicode )'},
       {d => 'love.mousepressed', t => 'called when any mouse button is pressed.<br><strong>x</strong>:number = mouse x position<br><strong>y</strong>:number = mouse y position<br><strong>button</strong>:MouseConstant = button pressed on mouse, r = right', i => '( x, y, button )'},
       {d => 'love.mousereleased', t => 'called when any mouse button is released.<br><strong>x</strong>:number = mouse x position<br><strong>y</strong>:number = mouse y position<br><strong>button</strong>:MouseConstant = button released on mouse, r = right', i => '( x, y, button )'},
       {d => 'love.joystickpressed', t => 'Called when a joystick button is pressed.<br>joystick:number = the joystick number, button:number = the button number', i => '( joystick, button )'},
       {d => 'love.joystickpressed', t => 'Called when a joystick button is pressed.<br>joystick:number = the joystick number, button:number = the button number', i => '( joystick, button )'},
       
       {d => 'love.audio.', t => 'provides an interface to create noise with the users speakers'},
       {d => 'love.event.', t => 'Manages events, like keypresses.'},
       {d => 'love.filesytem.', t => 'Provides an interface to the user\'s filesystem.'},
       {d => 'love.graphics.', t => 'The graphics module is responsible for things like Images, Animations, Fonts, etc.'},
       {d => 'love.image.', t => 'Provides an interface to decode encoded image data.'},
       {d => 'love.joystick.', t => 'Provides an interface to the user\'s joystick.'},
       {d => 'love.keyboard.', t => 'Provides an interface to the user\'s keyboard.'},
       {d => 'love.mouse.', t => 'Provides an interface to the user\'s mouse.'},
       {d => 'love.physics.', t => 'Simulates 2D rigid body physics in a realistic manner.'},
       {d => 'love.sound.', t => 'This module is responsible for decoding sound files.'},
       {d => 'love.timer.', t => 'Provides an interface to the user\'s clock.'},
       
       {d => 'love.audio.getNumSources', t => 'Gets the current number of simulatenous playing sources.', i => '( )'},
       {d => 'love.audio.getOrientation', t => 'Returns the orientation of the listener.', i => '( )'},
       {d => 'love.audio.getPosition', t => 'Returns the position of the listener.', i => '( )'},
       {d => 'love.audio.getVelocity', t => 'Returns the velocity of the listener.', i => '( )'},
       {d => 'love.audio.getVolume', t => 'Returns the master volume.', i => '( )'},
       {d => 'love.audio.newSource', t => 'Creates a new Source from a file. Sources created from SoundData are always static.<br><strong>file</strong>:string = The file to create a source from<br><strong>type</strong>:SourceType = Streaming or static source', i => '( ${1:file}, ${2:type} )'},
       {d => 'love.audio.pause', t => 'Pauses playback on the specified source or pauses all audio if argument nil.<br><strong>source</strong>:Source = The source on which you can pause playback. (optional)', i => '( ${1:source} )'},
       {d => 'love.audio.play', t => 'Plays the specified source.<br><strong>source</strong>:Source = The source to play.', i => '( ${1:source} )'},
       {d => 'love.audio.rewind', t => 'Rewinds source <em>or</em> all audio.<br><strong>source</strong>:Source = The sound to reqind. (optional)', i => '( ${1:source} )'},
       {d => 'love.audio.setOrientation', t => 'Sets the orientation of the listner.<br><strong>v</strong>:array = A float array of size 6 containing [x,y,z] for the forward vector, followed by [x,y,z] for the up vector.', i => '( ${1:v} )'},
       {d => 'love.audio.setPosition', t => 'Sets the position of the listener.<br><strong>v</strong>:array = A float array of size 3 containing [x,y,z] in that order', i => '( ${1:v} )'},
       {d => 'love.audio.setVelocity', t => 'Sets the velocity of the listener.<br><strong>x</strong>:number = The X velocity of the listner<br><strong>y</strong>:number = The Y velocity of the listener<br><strong>z</strong>:number = The Z velocity of the listener.', i => '( ${1:x}, ${2:y}, ${3:z} )'},
       {d => 'love.audio.setVolume', t => 'Sets the master volume.<br><strong>volume</strong>:number = 1.0 is max and 0.0 is off', i => '( ${1:volume} )'},
       {d => 'love.audio.stop', t => 'Stops playing the source <em>or<em> all audio.<br><strong>source</strong>:Source = The source to stop', i => '( ${1:source} )'},
       
       {d => 'love.event.poll', t => 'Gets an iterator for messages in the event queue.', i => '( )'},
       {d => 'love.event.push', t => 'Adds an event to the event queue.', i => '( ${1:e}, ${2:a}, ${3:b}, ${4:c} )'},
       {d => 'love.event.wait', t => 'Like love.event.poll, but blocks until there is an event in the queue.<br><u>returns</u> e, a, b, c', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
       {d => 'love.func', t => '', i => '(  )'},
]

